[project]
name = "hexlet-code"
version = "0.1.0"
description = "Task Manager Django project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=5.2.6",
    "django-bootstrap5>=25.2",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.1.1",
]
